const languages = [
  ["en", "English"],
  ["zh-Hans", "简体中文"],
  ["zh-Hant", "繁體中文"],
  ["es", "Español"],
  ["ja", "日本語"],
  ["ko", "한국어"],
  ["de", "Deutsch"],
  ["fr", "Français"],
  ["ru", "Русский"],
];

const en = {
  "nav.home": "Home",
  "nav.features": "Features",
  "nav.privacy": "Privacy Policy",
  "nav.support": "Support",
  "nav.language": "Language",
  "meta.description": "ChronosMap helps you explore people, events, photos, and movement over time on an interactive map.",
  "home.page.title": "ChronosMap - A map for time and place",
  "home.hero.title": "Read time on a map.",
  "home.hero.body": "ChronosMap is a time map app for iPhone, iPad, and Mac. It brings people, events, places, photos, and routes into one map and timeline, helping you understand stories through both space and time.",
  "home.hero.support": "Get support",
  "home.hero.privacy": "View privacy policy",
  "home.icon.alt": "ChronosMap app icon",
  "home.features.title": "Designed for history, people, and personal journeys.",
  "home.features.lead": "Open sample maps, import map packages, edit your own maps, and explore data with timelines, geo lenses, and density layers.",
  "home.feature.timeline.title": "Timeline browsing",
  "home.feature.timeline.body": "View events and person locations by year, date, or hour, and jump to real moments in the data.",
  "home.feature.lens.title": "Geo lens",
  "home.feature.lens.body": "Select an area on the map and see the events and trajectory points that happened there.",
  "home.feature.editor.title": "Map editing",
  "home.feature.editor.body": "Create your own maps with people, events, trajectory points, images, and ChronosMap files.",
  "home.feature.photos.title": "Build personal routes from photos",
  "home.feature.photos.body": "Import travel or everyday photos and ChronosMap can read their capture time and location to create personal trajectory points.",
  "home.photos.title": "Turn your photo library into a travel map.",
  "home.photos.lead": "Choose photos with location metadata, and ChronosMap creates trajectory points from their real coordinates and capture times. Each photo becomes a memory node for trips, city walks, field work, or personal timelines.",
  "home.photos.point1": "Uses the actual location recorded in each photo and does not merge photos with different coordinates.",
  "home.photos.point2": "Photos become part of the trajectory point content, so you can open richer image and text records later.",
  "home.photos.point3": "Your photo data is chosen and saved by you, making it suitable for private travel maps or shareable story maps.",
  "home.sample.title": "A built-in sample map.",
  "home.sample.lead": "The app includes a Tang Dynasty of China sample map that shows how people, events, and routes can be organized around time and place. You can also start from a blank map.",
  "home.sample.point1": "Supports sample maps and user-created maps.",
  "home.sample.point2": "Open from files, save as, import source data, and export source data.",
  "home.sample.point3": "Map data stays local and is managed and shared by you.",
  "home.sample.imageAlt": "Tang Chang'an map illustration",
  "privacy.page.title": "Privacy Policy - ChronosMap",
  "privacy.meta.description": "Privacy Policy for ChronosMap.",
  "privacy.title": "Privacy Policy",
  "privacy.updated": "Last updated: June 9, 2026",
  "privacy.intro": "ChronosMap respects your privacy. The app works with local map data, files you choose, and photos you choose. We do not create user accounts and do not actively collect, sell, or share personal data.",
  "privacy.noCollect.title": "Data we do not collect",
  "privacy.noCollect.item1": "We do not collect your name, email address, contacts, or precise location history.",
  "privacy.noCollect.item2": "We do not use third-party advertising SDKs.",
  "privacy.noCollect.item3": "We do not track in-app browsing behavior for advertising profiles.",
  "privacy.files.title": "Local files and photos",
  "privacy.files.body": "When you open, save, or import ChronosMap files, the app accesses only the files you explicitly choose. When importing photos to create trajectory points, the app may read capture time and location metadata from the photos you select. Photos and map content are saved on your device or in locations you choose.",
  "privacy.map.title": "Map services",
  "privacy.map.body": "ChronosMap uses Apple MapKit to display maps. Map tiles and base map services are provided by Apple and are subject to Apple's privacy policy.",
  "privacy.sharing.title": "Data sharing",
  "privacy.sharing.body": "You can export and share .chronosmap files or source packages yourself. Exported files may include text, images, times, and locations you added, so please review them before sharing.",
  "privacy.contact.title": "Contact",
  "privacy.contact.body": "If you have questions about this privacy policy, please contact us through the support page.",
  "support.page.title": "Support - ChronosMap",
  "support.meta.description": "Support page for ChronosMap.",
  "support.title": "Support",
  "support.intro": "If you run into a problem with ChronosMap, or want to send feedback about map editing, source data import, or photo trajectory points, you can contact us on GitHub.",
  "support.issue": "Report an issue",
  "support.repo": "View project",
  "support.faq.title": "FAQ",
  "support.faq.open": "How do I open a map? Open a sample map from the map library, or open a .chronosmap file from your device.",
  "support.faq.create": "How do I create a map? Enter edit mode to add people, events, and trajectory points, or import trajectory points from photos.",
  "support.faq.photo": "What happens when I import photos? The app reads time and location metadata from the photos you choose and uses them to create personal trajectory points.",
  "support.faq.data": "Is my data uploaded? ChronosMap mainly uses local files and local map data. Exported files are saved and shared by you.",
  "support.faq.platforms": "Which platforms are supported? ChronosMap is built for iPhone, iPad, and Mac.",
  "support.appStore.title": "App Store information",
  "support.appStore.body": "ChronosMap is planned as a one-time purchase app. This page will add the App Store link after release.",
};

const translations = {
  en,
  "zh-Hans": {
    ...en,
    "nav.home": "首页",
    "nav.features": "功能",
    "nav.privacy": "隐私政策",
    "nav.support": "支持",
    "nav.language": "语言",
    "meta.description": "ChronosMap 帮助你在交互式地图上探索人物、事件、照片和随时间变化的轨迹。",
    "home.page.title": "ChronosMap - 时间与地点的地图",
    "home.hero.title": "在地图上阅读时间。",
    "home.hero.body": "ChronosMap 是一款面向 iPhone、iPad 和 Mac 的时间地图应用。它把人物、事件、地点、照片和轨迹放在同一张地图与时间轴中，帮助你从空间和时间两个维度理解故事。",
    "home.hero.support": "获取支持",
    "home.hero.privacy": "查看隐私政策",
    "home.icon.alt": "ChronosMap App 图标",
    "home.features.title": "为历史、人物和旅行轨迹而设计。",
    "home.features.lead": "ChronosMap 支持打开示例地图、导入地图包、编辑自己的地图，并通过时间轴、地理透镜和热力层观察数据。",
    "home.feature.timeline.title": "时间轴浏览",
    "home.feature.timeline.body": "按年份、日期或小时查看事件与人物位置，快速跳转到真实发生的时间点。",
    "home.feature.lens.title": "地理透镜",
    "home.feature.lens.body": "在地图上选定一个范围，查看此地发生过的事件和人物轨迹点。",
    "home.feature.editor.title": "地图编辑",
    "home.feature.editor.body": "创建自己的地图，添加人物、事件、轨迹点和图片，保存为 ChronosMap 地图文件。",
    "home.feature.photos.title": "照片生成个人轨迹",
    "home.feature.photos.body": "导入旅行或日常照片，ChronosMap 会读取照片中的拍摄时间和地理位置，为你自动创建个人轨迹点。",
    "home.photos.title": "把相册变成你的旅行地图。",
    "home.photos.lead": "选择带有位置信息的照片，应用会按照片真实经纬度和拍摄时间建立轨迹点。每张照片都可以成为旅程中的一个记忆节点，适合整理旅行、城市漫步、考察路线或个人年表。",
    "home.photos.point1": "严格使用照片记录的实际位置，不自动合并不同经纬度的照片。",
    "home.photos.point2": "照片会作为轨迹点内容的一部分，点击后可查看更完整的图片和文字记录。",
    "home.photos.point3": "照片数据由你选择和保存，适合制作私人的旅行地图或公开分享的故事地图。",
    "home.sample.title": "内置示例地图。",
    "home.sample.lead": "应用内置“中国唐朝”示例地图，展示人物、事件和轨迹如何围绕地点与时间组织起来。你也可以从空白地图开始创作自己的数据。",
    "home.sample.point1": "支持示例地图和用户自制地图。",
    "home.sample.point2": "支持从文件打开、另存、导入源数据和导出源数据。",
    "home.sample.point3": "地图数据保存在本地，用户自行管理和分享。",
    "home.sample.imageAlt": "唐代长安地图示意图",
    "privacy.page.title": "隐私政策 - ChronosMap",
    "privacy.meta.description": "ChronosMap 隐私政策。",
    "privacy.title": "隐私政策",
    "privacy.updated": "最后更新：2026 年 6 月 9 日",
    "privacy.intro": "ChronosMap 尊重你的隐私。应用的核心功能围绕本地地图数据、用户选择的文件和用户选择的照片展开。我们不会建立用户账号，也不会主动收集、出售或共享个人数据。",
    "privacy.noCollect.title": "我们不收集的数据",
    "privacy.noCollect.item1": "我们不收集你的姓名、邮箱、通讯录或精确位置历史。",
    "privacy.noCollect.item2": "我们不使用第三方广告 SDK。",
    "privacy.noCollect.item3": "我们不追踪你在应用中的浏览行为用于广告画像。",
    "privacy.files.title": "本地文件和照片",
    "privacy.files.body": "当你打开、保存或导入 ChronosMap 地图文件时，应用只会访问你明确选择的文件。导入照片生成轨迹点时，应用会读取你选择照片中的拍摄时间和地理位置信息，用于创建地图内容。照片和地图内容由你保存在本地设备或你选择的位置。",
    "privacy.map.title": "地图服务",
    "privacy.map.body": "ChronosMap 使用 Apple MapKit 显示地图。地图瓦片和基础地图服务由 Apple 提供，相关数据处理受 Apple 的隐私政策约束。",
    "privacy.sharing.title": "数据分享",
    "privacy.sharing.body": "你可以自行导出和分享 .chronosmap 文件或源数据包。导出文件中可能包含你添加的文字、图片、时间和地点信息，请在分享前确认内容适合公开。",
    "privacy.contact.title": "联系我们",
    "privacy.contact.body": "如果你对隐私政策有疑问，请通过支持页面联系我们。",
    "support.page.title": "支持 - ChronosMap",
    "support.meta.description": "ChronosMap 支持页面。",
    "support.title": "支持",
    "support.intro": "如果你在使用 ChronosMap 时遇到问题，或者希望反馈地图编辑、数据包导入、照片轨迹点等功能的建议，可以通过 GitHub 与我们联系。",
    "support.issue": "提交问题",
    "support.repo": "查看项目",
    "support.faq.title": "常见问题",
    "support.faq.open": "如何打开地图？你可以从地图库打开示例地图，也可以从文件打开 .chronosmap 地图。",
    "support.faq.create": "如何创建地图？进入编辑模式后，可以添加人物、事件和轨迹点，也可以从照片导入轨迹点。",
    "support.faq.photo": "照片导入会怎样处理？应用会读取你选择照片中的时间和位置，用它们创建个人轨迹点。",
    "support.faq.data": "数据会上传吗？ChronosMap 主要使用本地文件和本地地图数据；你导出的文件由你自己保存和分享。",
    "support.faq.platforms": "支持哪些平台？ChronosMap 面向 iPhone、iPad 和 Mac。",
    "support.appStore.title": "App Store 信息",
    "support.appStore.body": "ChronosMap 计划采用一次性购买模式。上线后，此页面会补充 App Store 下载链接。",
  },
  "zh-Hant": {
    ...en,
    "nav.home": "首頁",
    "nav.features": "功能",
    "nav.privacy": "隱私政策",
    "nav.support": "支援",
    "nav.language": "語言",
    "meta.description": "ChronosMap 幫助你在互動式地圖上探索人物、事件、照片和隨時間變化的軌跡。",
    "home.page.title": "ChronosMap - 時間與地點的地圖",
    "home.hero.title": "在地圖上閱讀時間。",
    "home.hero.body": "ChronosMap 是一款面向 iPhone、iPad 和 Mac 的時間地圖應用。它把人物、事件、地點、照片和軌跡放在同一張地圖與時間軸中，幫助你從空間和時間兩個維度理解故事。",
    "home.hero.support": "取得支援",
    "home.hero.privacy": "查看隱私政策",
    "home.icon.alt": "ChronosMap App 圖示",
    "home.features.title": "為歷史、人物和旅行軌跡而設計。",
    "home.features.lead": "ChronosMap 支援開啟示例地圖、匯入地圖包、編輯自己的地圖，並透過時間軸、地理透鏡和熱力層觀察資料。",
    "home.feature.timeline.title": "時間軸瀏覽",
    "home.feature.timeline.body": "按年份、日期或小時查看事件與人物位置，快速跳轉到真實發生的時間點。",
    "home.feature.lens.title": "地理透鏡",
    "home.feature.lens.body": "在地圖上選定一個範圍，查看此地發生過的事件和人物軌跡點。",
    "home.feature.editor.title": "地圖編輯",
    "home.feature.editor.body": "建立自己的地圖，加入人物、事件、軌跡點和圖片，儲存為 ChronosMap 地圖檔案。",
    "home.feature.photos.title": "照片生成個人軌跡",
    "home.feature.photos.body": "匯入旅行或日常照片，ChronosMap 會讀取照片中的拍攝時間和地理位置，為你自動建立個人軌跡點。",
    "home.photos.title": "把相簿變成你的旅行地圖。",
    "home.photos.lead": "選擇帶有位置資訊的照片，應用會按照片真實經緯度和拍攝時間建立軌跡點。每張照片都可以成為旅程中的記憶節點，適合整理旅行、城市漫步、考察路線或個人年表。",
    "home.photos.point1": "嚴格使用照片記錄的實際位置，不自動合併不同經緯度的照片。",
    "home.photos.point2": "照片會作為軌跡點內容的一部分，點擊後可查看更完整的圖片和文字記錄。",
    "home.photos.point3": "照片資料由你選擇和保存，適合製作私人的旅行地圖或公開分享的故事地圖。",
    "home.sample.title": "內建示例地圖。",
    "home.sample.lead": "應用內建「中國唐朝」示例地圖，展示人物、事件和軌跡如何圍繞地點與時間組織起來。你也可以從空白地圖開始創作自己的資料。",
    "home.sample.point1": "支援示例地圖和使用者自製地圖。",
    "home.sample.point2": "支援從檔案開啟、另存、匯入來源資料和匯出來源資料。",
    "home.sample.point3": "地圖資料保存在本機，由你自行管理和分享。",
    "home.sample.imageAlt": "唐代長安地圖示意圖",
    "privacy.page.title": "隱私政策 - ChronosMap",
    "privacy.meta.description": "ChronosMap 隱私政策。",
    "privacy.title": "隱私政策",
    "privacy.updated": "最後更新：2026 年 6 月 9 日",
    "privacy.intro": "ChronosMap 尊重你的隱私。應用的核心功能圍繞本機地圖資料、你選擇的檔案和照片。我們不會建立使用者帳號，也不會主動收集、出售或共享個人資料。",
    "privacy.noCollect.title": "我們不收集的資料",
    "privacy.noCollect.item1": "我們不收集你的姓名、電子郵件、通訊錄或精確位置歷史。",
    "privacy.noCollect.item2": "我們不使用第三方廣告 SDK。",
    "privacy.noCollect.item3": "我們不追蹤你在應用中的瀏覽行為用於廣告画像。",
    "privacy.files.title": "本機檔案和照片",
    "privacy.files.body": "當你開啟、儲存或匯入 ChronosMap 地圖檔案時，應用只會存取你明確選擇的檔案。匯入照片建立軌跡點時，應用可能會讀取你選擇照片中的拍攝時間和位置資訊。照片和地圖內容會保存在你的裝置或你選擇的位置。",
    "privacy.map.title": "地圖服務",
    "privacy.map.body": "ChronosMap 使用 Apple MapKit 顯示地圖。地圖圖磚和基礎地圖服務由 Apple 提供，相關資料處理受 Apple 隱私政策約束。",
    "privacy.sharing.title": "資料分享",
    "privacy.sharing.body": "你可以自行匯出和分享 .chronosmap 檔案或來源資料包。匯出檔案可能包含你加入的文字、圖片、時間和地點資訊，分享前請先確認內容適合公開。",
    "privacy.contact.title": "聯絡我們",
    "privacy.contact.body": "如果你對隱私政策有疑問，請透過支援頁面聯絡我們。",
    "support.page.title": "支援 - ChronosMap",
    "support.meta.description": "ChronosMap 支援頁面。",
    "support.title": "支援",
    "support.intro": "如果你在使用 ChronosMap 時遇到問題，或希望回饋地圖編輯、來源資料匯入、照片軌跡點等功能建議，可以透過 GitHub 與我們聯絡。",
    "support.issue": "提交問題",
    "support.repo": "查看專案",
    "support.faq.title": "常見問題",
    "support.faq.open": "如何開啟地圖？你可以從地圖庫開啟示例地圖，也可以從檔案開啟 .chronosmap 地圖。",
    "support.faq.create": "如何建立地圖？進入編輯模式後，可以加入人物、事件和軌跡點，也可以從照片匯入軌跡點。",
    "support.faq.photo": "照片匯入會如何處理？應用會讀取你選擇照片中的時間和位置，用它們建立個人軌跡點。",
    "support.faq.data": "資料會上傳嗎？ChronosMap 主要使用本機檔案和本機地圖資料；匯出的檔案由你自行保存和分享。",
    "support.faq.platforms": "支援哪些平台？ChronosMap 面向 iPhone、iPad 和 Mac。",
    "support.appStore.title": "App Store 資訊",
    "support.appStore.body": "ChronosMap 計畫採用一次性購買模式。上線後，此頁面會補充 App Store 下載連結。",
  },
};

translations.es = {
  ...en,
  "nav.home": "Inicio",
  "nav.features": "Funciones",
  "nav.privacy": "Privacidad",
  "nav.support": "Soporte",
  "nav.language": "Idioma",
  "home.page.title": "ChronosMap - Un mapa para tiempo y lugar",
  "home.hero.title": "Lee el tiempo sobre un mapa.",
  "home.hero.body": "ChronosMap es una app de mapas temporales para iPhone, iPad y Mac. Reúne personas, eventos, lugares, fotos y recorridos en un mapa con línea de tiempo.",
  "home.features.title": "Diseñada para historia, personas y viajes personales.",
  "home.feature.photos.title": "Crea rutas personales desde fotos",
  "home.feature.photos.body": "Importa fotos de viajes o del día a día; ChronosMap lee la hora y ubicación para crear puntos de trayectoria.",
  "home.photos.title": "Convierte tu biblioteca de fotos en un mapa de viaje.",
  "home.photos.lead": "Elige fotos con metadatos de ubicación y ChronosMap crea puntos con sus coordenadas y horas reales. Cada foto puede ser un nodo de memoria para viajes, caminatas o líneas de vida.",
  "privacy.title": "Política de privacidad",
  "privacy.updated": "Última actualización: 9 de junio de 2026",
  "support.title": "Soporte",
  "support.faq.title": "Preguntas frecuentes",
};

translations.ja = {
  ...en,
  "nav.home": "ホーム",
  "nav.features": "機能",
  "nav.privacy": "プライバシー",
  "nav.support": "サポート",
  "nav.language": "言語",
  "home.page.title": "ChronosMap - 時間と場所の地図",
  "home.hero.title": "地図の上で時間を読む。",
  "home.hero.body": "ChronosMap は iPhone、iPad、Mac 向けの時間地図アプリです。人物、出来事、場所、写真、移動をひとつの地図とタイムラインで整理します。",
  "home.features.title": "歴史、人物、旅の軌跡のために設計。",
  "home.feature.photos.title": "写真から個人ルートを作成",
  "home.feature.photos.body": "旅行や日常の写真を読み込み、撮影時刻と位置情報から軌跡ポイントを作成します。",
  "home.photos.title": "写真ライブラリを旅の地図に。",
  "home.photos.lead": "位置情報を含む写真を選ぶと、ChronosMap は実際の座標と撮影時刻から軌跡ポイントを作成します。各写真は旅、街歩き、調査、個人年表の記憶ノードになります。",
  "privacy.title": "プライバシーポリシー",
  "privacy.updated": "最終更新日：2026年6月9日",
  "support.title": "サポート",
  "support.faq.title": "よくある質問",
};

translations.ko = {
  ...en,
  "nav.home": "홈",
  "nav.features": "기능",
  "nav.privacy": "개인정보 처리방침",
  "nav.support": "지원",
  "nav.language": "언어",
  "home.page.title": "ChronosMap - 시간과 장소의 지도",
  "home.hero.title": "지도 위에서 시간을 읽다.",
  "home.hero.body": "ChronosMap은 iPhone, iPad, Mac용 시간 지도 앱입니다. 인물, 사건, 장소, 사진, 이동 경로를 하나의 지도와 타임라인에 담습니다.",
  "home.features.title": "역사, 인물, 개인 여행 경로를 위해 설계되었습니다.",
  "home.feature.photos.title": "사진으로 개인 경로 만들기",
  "home.feature.photos.body": "여행 또는 일상 사진을 가져오면 ChronosMap이 촬영 시간과 위치를 읽어 궤적 지점을 만듭니다.",
  "home.photos.title": "사진 보관함을 여행 지도로 바꾸세요.",
  "home.photos.lead": "위치 메타데이터가 있는 사진을 선택하면 ChronosMap이 실제 좌표와 촬영 시간으로 궤적 지점을 만듭니다. 각 사진은 여행, 도시 산책, 현장 조사, 개인 연표의 기억 노드가 됩니다.",
  "privacy.title": "개인정보 처리방침",
  "privacy.updated": "최종 업데이트: 2026년 6월 9일",
  "support.title": "지원",
  "support.faq.title": "자주 묻는 질문",
};

translations.de = {
  ...en,
  "nav.home": "Start",
  "nav.features": "Funktionen",
  "nav.privacy": "Datenschutz",
  "nav.support": "Support",
  "nav.language": "Sprache",
  "home.page.title": "ChronosMap - Eine Karte für Zeit und Ort",
  "home.hero.title": "Zeit auf einer Karte lesen.",
  "home.hero.body": "ChronosMap ist eine Zeitkarten-App für iPhone, iPad und Mac. Sie verbindet Personen, Ereignisse, Orte, Fotos und Wege in einer Karte mit Zeitleiste.",
  "home.features.title": "Für Geschichte, Personen und persönliche Reisen gestaltet.",
  "home.feature.photos.title": "Persönliche Routen aus Fotos",
  "home.feature.photos.body": "Importiere Reise- oder Alltagsfotos; ChronosMap liest Aufnahmezeit und Ort und erstellt daraus Trajektorienpunkte.",
  "home.photos.title": "Verwandle deine Fotomediathek in eine Reisekarte.",
  "home.photos.lead": "Wähle Fotos mit Ortsmetadaten. ChronosMap erstellt Punkte aus realen Koordinaten und Aufnahmezeiten. Jedes Foto wird zu einem Erinnerungspunkt für Reisen, Stadtspaziergänge oder persönliche Zeitleisten.",
  "privacy.title": "Datenschutzerklärung",
  "privacy.updated": "Zuletzt aktualisiert: 9. Juni 2026",
  "support.title": "Support",
  "support.faq.title": "FAQ",
};

translations.fr = {
  ...en,
  "nav.home": "Accueil",
  "nav.features": "Fonctions",
  "nav.privacy": "Confidentialité",
  "nav.support": "Assistance",
  "nav.language": "Langue",
  "home.page.title": "ChronosMap - Une carte du temps et des lieux",
  "home.hero.title": "Lire le temps sur une carte.",
  "home.hero.body": "ChronosMap est une app de carte temporelle pour iPhone, iPad et Mac. Elle rassemble personnes, événements, lieux, photos et trajets dans une carte avec chronologie.",
  "home.features.title": "Pensée pour l'histoire, les personnes et les voyages personnels.",
  "home.feature.photos.title": "Créer des trajets depuis des photos",
  "home.feature.photos.body": "Importez des photos de voyage ou du quotidien ; ChronosMap lit l'heure et le lieu de prise de vue pour créer des points de trajectoire.",
  "home.photos.title": "Transformez votre photothèque en carte de voyage.",
  "home.photos.lead": "Choisissez des photos avec métadonnées de localisation. ChronosMap crée des points depuis leurs coordonnées et heures réelles. Chaque photo devient un souvenir pour voyages, promenades, enquêtes ou chronologies personnelles.",
  "privacy.title": "Politique de confidentialité",
  "privacy.updated": "Dernière mise à jour : 9 juin 2026",
  "support.title": "Assistance",
  "support.faq.title": "Questions fréquentes",
};

translations.ru = {
  ...en,
  "nav.home": "Главная",
  "nav.features": "Возможности",
  "nav.privacy": "Конфиденциальность",
  "nav.support": "Поддержка",
  "nav.language": "Язык",
  "home.page.title": "ChronosMap - карта времени и мест",
  "home.hero.title": "Читайте время на карте.",
  "home.hero.body": "ChronosMap — приложение временных карт для iPhone, iPad и Mac. Оно объединяет людей, события, места, фотографии и маршруты на одной карте с временной шкалой.",
  "home.features.title": "Для истории, людей и личных путешествий.",
  "home.feature.photos.title": "Личные маршруты из фотографий",
  "home.feature.photos.body": "Импортируйте фотографии путешествий или повседневной жизни, и ChronosMap создаст точки маршрута по времени съемки и геопозиции.",
  "home.photos.title": "Превратите фотобиблиотеку в карту путешествия.",
  "home.photos.lead": "Выберите фотографии с геоданными, и ChronosMap создаст точки по реальным координатам и времени съемки. Каждое фото становится узлом памяти для поездок, прогулок, исследований или личной хроники.",
  "privacy.title": "Политика конфиденциальности",
  "privacy.updated": "Обновлено: 9 июня 2026 г.",
  "support.title": "Поддержка",
  "support.faq.title": "Вопросы и ответы",
};

Object.assign(translations.es, {
  "meta.description": "ChronosMap te ayuda a explorar personas, eventos, fotos y movimientos en el tiempo sobre un mapa interactivo.",
  "home.hero.support": "Obtener soporte",
  "home.hero.privacy": "Ver política de privacidad",
  "home.icon.alt": "Icono de la app ChronosMap",
  "home.features.lead": "Abre mapas de ejemplo, importa paquetes, edita tus propios mapas y explora datos con líneas de tiempo, lentes geográficas y capas de densidad.",
  "home.feature.timeline.title": "Exploración temporal",
  "home.feature.timeline.body": "Consulta eventos y ubicaciones de personas por año, fecha u hora, y salta a momentos reales de los datos.",
  "home.feature.lens.title": "Lente geográfica",
  "home.feature.lens.body": "Selecciona un área del mapa y ve los eventos y puntos de trayectoria que ocurrieron allí.",
  "home.feature.editor.title": "Edición de mapas",
  "home.feature.editor.body": "Crea mapas propios con personas, eventos, puntos de trayectoria, imágenes y archivos ChronosMap.",
  "home.photos.point1": "Usa la ubicación real registrada en cada foto y no fusiona fotos con coordenadas diferentes.",
  "home.photos.point2": "Las fotos pasan a formar parte del contenido del punto de trayectoria para ver registros más ricos con imagen y texto.",
  "home.photos.point3": "Tus fotos son elegidas y guardadas por ti, ideal para mapas privados de viaje o historias compartibles.",
  "home.sample.title": "Mapa de ejemplo incluido.",
  "home.sample.lead": "La app incluye un mapa de ejemplo de la dinastía Tang de China que muestra cómo organizar personas, eventos y rutas por tiempo y lugar.",
  "home.sample.point1": "Admite mapas de ejemplo y mapas creados por usuarios.",
  "home.sample.point2": "Abrir desde archivos, guardar como, importar datos fuente y exportar datos fuente.",
  "home.sample.point3": "Los datos del mapa permanecen locales y los gestionas y compartes tú.",
  "home.sample.imageAlt": "Ilustración del mapa de Chang'an Tang",
  "privacy.page.title": "Política de privacidad - ChronosMap",
  "privacy.meta.description": "Política de privacidad de ChronosMap.",
  "privacy.intro": "ChronosMap respeta tu privacidad. La app trabaja con datos locales de mapas, archivos que eliges y fotos que eliges. No creamos cuentas de usuario ni recopilamos, vendemos o compartimos datos personales de forma activa.",
  "privacy.noCollect.title": "Datos que no recopilamos",
  "privacy.noCollect.item1": "No recopilamos tu nombre, correo electrónico, contactos ni historial de ubicación precisa.",
  "privacy.noCollect.item2": "No usamos SDK de publicidad de terceros.",
  "privacy.noCollect.item3": "No rastreamos tu uso de la app para perfiles publicitarios.",
  "privacy.files.title": "Archivos locales y fotos",
  "privacy.files.body": "Al abrir, guardar o importar archivos ChronosMap, la app accede solo a los archivos que eliges explícitamente. Al importar fotos para crear puntos de trayectoria, puede leer la hora de captura y la ubicación de las fotos seleccionadas.",
  "privacy.map.title": "Servicios de mapas",
  "privacy.map.body": "ChronosMap usa Apple MapKit para mostrar mapas. Los mosaicos y servicios base son proporcionados por Apple y se rigen por su política de privacidad.",
  "privacy.sharing.title": "Compartir datos",
  "privacy.sharing.body": "Puedes exportar y compartir archivos .chronosmap o paquetes fuente. Los archivos exportados pueden incluir texto, imágenes, horas y ubicaciones que añadiste.",
  "privacy.contact.title": "Contacto",
  "privacy.contact.body": "Si tienes preguntas sobre esta política, contáctanos desde la página de soporte.",
  "support.page.title": "Soporte - ChronosMap",
  "support.meta.description": "Página de soporte de ChronosMap.",
  "support.intro": "Si tienes un problema con ChronosMap o quieres enviar comentarios sobre edición, importación de datos o puntos desde fotos, contáctanos en GitHub.",
  "support.issue": "Enviar problema",
  "support.repo": "Ver proyecto",
  "support.faq.open": "¿Cómo abro un mapa? Abre un mapa de ejemplo desde la biblioteca o un archivo .chronosmap desde tu dispositivo.",
  "support.faq.create": "¿Cómo creo un mapa? Entra en modo edición para añadir personas, eventos y trayectorias, o importa puntos desde fotos.",
  "support.faq.photo": "¿Qué ocurre al importar fotos? La app lee la hora y ubicación de las fotos elegidas para crear puntos de trayectoria personales.",
  "support.faq.data": "¿Se suben mis datos? ChronosMap usa principalmente archivos locales; tú guardas y compartes los archivos exportados.",
  "support.faq.platforms": "¿Qué plataformas admite? ChronosMap está hecho para iPhone, iPad y Mac.",
  "support.appStore.title": "Información de App Store",
  "support.appStore.body": "ChronosMap está previsto como app de compra única. Añadiremos el enlace de App Store tras el lanzamiento.",
});

Object.assign(translations.ja, {
  "meta.description": "ChronosMap は人物、出来事、写真、移動を時間とともにインタラクティブな地図で探索できます。",
  "home.hero.support": "サポートを見る",
  "home.hero.privacy": "プライバシーポリシー",
  "home.icon.alt": "ChronosMap アプリアイコン",
  "home.features.lead": "サンプル地図の表示、地図パッケージの読み込み、自分の地図の編集、タイムライン、地理レンズ、密度レイヤーでの探索に対応します。",
  "home.feature.timeline.title": "タイムライン閲覧",
  "home.feature.timeline.body": "年、日付、時刻ごとに出来事や人物の位置を見て、実際の時点へ移動できます。",
  "home.feature.lens.title": "地理レンズ",
  "home.feature.lens.body": "地図上の範囲を選び、その場所で起きた出来事や軌跡ポイントを確認できます。",
  "home.feature.editor.title": "地図編集",
  "home.feature.editor.body": "人物、出来事、軌跡ポイント、画像を含む自分の ChronosMap 地図を作成できます。",
  "home.photos.point1": "各写真に記録された実際の位置を使い、座標が異なる写真を自動統合しません。",
  "home.photos.point2": "写真は軌跡ポイントの内容となり、あとから画像と文章の記録を開けます。",
  "home.photos.point3": "写真データはあなたが選んで保存するため、個人の旅行地図にも共有用の物語地図にも使えます。",
  "home.sample.title": "内蔵サンプル地図。",
  "home.sample.lead": "中国唐代のサンプル地図で、人物、出来事、経路を時間と場所で整理する方法を確認できます。",
  "home.sample.point1": "サンプル地図とユーザー作成地図に対応。",
  "home.sample.point2": "ファイルから開く、別名保存、ソースデータの読み込みと書き出しに対応。",
  "home.sample.point3": "地図データはローカルに保存され、管理と共有はあなたが行います。",
  "home.sample.imageAlt": "唐代長安の地図イラスト",
  "privacy.page.title": "プライバシーポリシー - ChronosMap",
  "privacy.meta.description": "ChronosMap のプライバシーポリシー。",
  "privacy.intro": "ChronosMap はプライバシーを尊重します。アプリはローカルの地図データ、あなたが選んだファイルと写真を扱います。ユーザーアカウントを作成せず、個人データを積極的に収集、販売、共有しません。",
  "privacy.noCollect.title": "収集しないデータ",
  "privacy.noCollect.item1": "氏名、メールアドレス、連絡先、正確な位置履歴は収集しません。",
  "privacy.noCollect.item2": "第三者広告 SDK は使用しません。",
  "privacy.noCollect.item3": "広告プロファイル作成のためにアプリ内行動を追跡しません。",
  "privacy.files.title": "ローカルファイルと写真",
  "privacy.files.body": "ChronosMap ファイルを開く、保存、読み込むとき、アプリは明示的に選択されたファイルだけにアクセスします。写真から軌跡ポイントを作成するとき、選択した写真の撮影時刻と位置情報を読む場合があります。",
  "privacy.map.title": "地図サービス",
  "privacy.map.body": "ChronosMap は地図表示に Apple MapKit を使用します。地図タイルと基本サービスは Apple により提供され、Apple のプライバシーポリシーが適用されます。",
  "privacy.sharing.title": "データ共有",
  "privacy.sharing.body": ".chronosmap ファイルやソースパッケージは自分で書き出して共有できます。書き出しファイルには追加した文章、画像、時刻、場所が含まれる場合があります。",
  "privacy.contact.title": "お問い合わせ",
  "privacy.contact.body": "このポリシーについて質問がある場合は、サポートページからご連絡ください。",
  "support.page.title": "サポート - ChronosMap",
  "support.meta.description": "ChronosMap のサポートページ。",
  "support.intro": "ChronosMap の問題や、地図編集、ソースデータ読み込み、写真軌跡ポイントに関する意見は GitHub からお寄せください。",
  "support.issue": "問題を報告",
  "support.repo": "プロジェクトを見る",
  "support.faq.open": "地図を開くには？地図ライブラリのサンプル、または端末上の .chronosmap ファイルを開けます。",
  "support.faq.create": "地図を作るには？編集モードで人物、出来事、軌跡ポイントを追加し、写真からも読み込めます。",
  "support.faq.photo": "写真読み込みでは？選択した写真の時刻と位置を読み取り、個人の軌跡ポイントを作成します。",
  "support.faq.data": "データはアップロードされますか？主にローカルファイルを使用し、書き出しファイルはあなたが保存、共有します。",
  "support.faq.platforms": "対応プラットフォームは？iPhone、iPad、Mac に対応します。",
  "support.appStore.title": "App Store 情報",
  "support.appStore.body": "ChronosMap は買い切りアプリとして提供予定です。公開後に App Store リンクを追加します。",
});

Object.assign(translations.ko, {
  "meta.description": "ChronosMap은 인물, 사건, 사진, 이동 경로를 시간에 따라 인터랙티브 지도에서 탐색하도록 돕습니다.",
  "home.hero.support": "지원 받기",
  "home.hero.privacy": "개인정보 처리방침 보기",
  "home.icon.alt": "ChronosMap 앱 아이콘",
  "home.features.lead": "예시 지도 열기, 지도 패키지 가져오기, 나만의 지도 편집, 타임라인·지리 렌즈·밀도 레이어 탐색을 지원합니다.",
  "home.feature.timeline.title": "타임라인 탐색",
  "home.feature.timeline.body": "연도, 날짜, 시간 단위로 사건과 인물 위치를 보고 실제 시점으로 이동할 수 있습니다.",
  "home.feature.lens.title": "지리 렌즈",
  "home.feature.lens.body": "지도에서 범위를 선택해 그곳에서 발생한 사건과 궤적 지점을 확인합니다.",
  "home.feature.editor.title": "지도 편집",
  "home.feature.editor.body": "인물, 사건, 궤적 지점, 이미지가 포함된 ChronosMap 지도를 만들 수 있습니다.",
  "home.photos.point1": "각 사진에 기록된 실제 위치를 사용하며 좌표가 다른 사진을 자동 병합하지 않습니다.",
  "home.photos.point2": "사진은 궤적 지점 콘텐츠가 되어 나중에 이미지와 글 기록을 열 수 있습니다.",
  "home.photos.point3": "사진 데이터는 사용자가 선택하고 저장하므로 개인 여행 지도나 공유 가능한 이야기 지도에 적합합니다.",
  "home.sample.title": "내장 예시 지도.",
  "home.sample.lead": "중국 당나라 예시 지도로 인물, 사건, 경로가 시간과 장소를 중심으로 조직되는 방식을 볼 수 있습니다.",
  "home.sample.point1": "예시 지도와 사용자 제작 지도를 지원합니다.",
  "home.sample.point2": "파일 열기, 다른 이름 저장, 원본 데이터 가져오기와 내보내기를 지원합니다.",
  "home.sample.point3": "지도 데이터는 로컬에 남으며 사용자가 관리하고 공유합니다.",
  "home.sample.imageAlt": "당나라 장안 지도 일러스트",
  "privacy.page.title": "개인정보 처리방침 - ChronosMap",
  "privacy.meta.description": "ChronosMap 개인정보 처리방침.",
  "privacy.intro": "ChronosMap은 개인정보를 존중합니다. 앱은 로컬 지도 데이터, 사용자가 선택한 파일과 사진을 다룹니다. 사용자 계정을 만들지 않으며 개인정보를 적극적으로 수집, 판매, 공유하지 않습니다.",
  "privacy.noCollect.title": "수집하지 않는 데이터",
  "privacy.noCollect.item1": "이름, 이메일, 연락처 또는 정확한 위치 기록을 수집하지 않습니다.",
  "privacy.noCollect.item2": "타사 광고 SDK를 사용하지 않습니다.",
  "privacy.noCollect.item3": "광고 프로필을 위해 앱 내 행동을 추적하지 않습니다.",
  "privacy.files.title": "로컬 파일과 사진",
  "privacy.files.body": "ChronosMap 파일을 열거나 저장하거나 가져올 때 앱은 사용자가 명시적으로 선택한 파일에만 접근합니다. 사진으로 궤적 지점을 만들 때 선택한 사진의 촬영 시간과 위치 메타데이터를 읽을 수 있습니다.",
  "privacy.map.title": "지도 서비스",
  "privacy.map.body": "ChronosMap은 지도 표시를 위해 Apple MapKit을 사용합니다. 지도 타일과 기본 서비스는 Apple이 제공하며 Apple 개인정보 정책이 적용됩니다.",
  "privacy.sharing.title": "데이터 공유",
  "privacy.sharing.body": ".chronosmap 파일이나 원본 패키지를 직접 내보내고 공유할 수 있습니다. 내보낸 파일에는 추가한 텍스트, 이미지, 시간, 위치가 포함될 수 있습니다.",
  "privacy.contact.title": "문의",
  "privacy.contact.body": "이 개인정보 처리방침에 대한 질문은 지원 페이지를 통해 연락해 주세요.",
  "support.page.title": "지원 - ChronosMap",
  "support.meta.description": "ChronosMap 지원 페이지.",
  "support.intro": "ChronosMap 사용 중 문제나 지도 편집, 원본 데이터 가져오기, 사진 궤적 지점에 대한 의견은 GitHub로 보내 주세요.",
  "support.issue": "문제 신고",
  "support.repo": "프로젝트 보기",
  "support.faq.open": "지도를 여는 방법은? 지도 라이브러리의 예시 지도나 기기의 .chronosmap 파일을 열 수 있습니다.",
  "support.faq.create": "지도를 만드는 방법은? 편집 모드에서 인물, 사건, 궤적 지점을 추가하거나 사진에서 가져올 수 있습니다.",
  "support.faq.photo": "사진 가져오기는 어떻게 처리되나요? 선택한 사진의 시간과 위치를 읽어 개인 궤적 지점을 만듭니다.",
  "support.faq.data": "데이터가 업로드되나요? ChronosMap은 주로 로컬 파일을 사용하며 내보낸 파일은 사용자가 저장하고 공유합니다.",
  "support.faq.platforms": "지원 플랫폼은? ChronosMap은 iPhone, iPad, Mac용입니다.",
  "support.appStore.title": "App Store 정보",
  "support.appStore.body": "ChronosMap은 일회성 구매 앱으로 제공될 예정입니다. 출시 후 App Store 링크를 추가합니다.",
});

Object.assign(translations.de, {
  "meta.description": "ChronosMap hilft, Personen, Ereignisse, Fotos und Bewegungen über die Zeit auf einer interaktiven Karte zu erkunden.",
  "home.hero.support": "Support erhalten",
  "home.hero.privacy": "Datenschutz ansehen",
  "home.icon.alt": "ChronosMap App-Symbol",
  "home.features.lead": "Öffne Beispielkarten, importiere Kartenpakete, bearbeite eigene Karten und erkunde Daten mit Zeitleisten, Geo-Linsen und Dichteebenen.",
  "home.feature.timeline.title": "Zeitleistenansicht",
  "home.feature.timeline.body": "Sieh Ereignisse und Personenpositionen nach Jahr, Datum oder Stunde und springe zu echten Datenpunkten.",
  "home.feature.lens.title": "Geo-Linse",
  "home.feature.lens.body": "Wähle einen Bereich auf der Karte und sieh Ereignisse und Trajektorienpunkte an diesem Ort.",
  "home.feature.editor.title": "Kartenbearbeitung",
  "home.feature.editor.body": "Erstelle eigene Karten mit Personen, Ereignissen, Trajektorienpunkten, Bildern und ChronosMap-Dateien.",
  "home.photos.point1": "Nutzt den tatsächlichen Standort jeder Fotoaufnahme und führt Fotos mit unterschiedlichen Koordinaten nicht zusammen.",
  "home.photos.point2": "Fotos werden Teil des Trajektorienpunkts, sodass spätere Bild- und Textaufzeichnungen möglich sind.",
  "home.photos.point3": "Fotodaten werden von dir ausgewählt und gespeichert, passend für private Reisekarten oder teilbare Story-Karten.",
  "home.sample.title": "Integrierte Beispielkarte.",
  "home.sample.lead": "Die App enthält eine Beispielkarte zur Tang-Dynastie Chinas und zeigt, wie Personen, Ereignisse und Routen nach Zeit und Ort organisiert werden.",
  "home.sample.point1": "Unterstützt Beispielkarten und nutzergenerierte Karten.",
  "home.sample.point2": "Aus Dateien öffnen, speichern unter, Quelldaten importieren und exportieren.",
  "home.sample.point3": "Kartendaten bleiben lokal und werden von dir verwaltet und geteilt.",
  "home.sample.imageAlt": "Illustration der Tang-Karte von Chang'an",
  "privacy.page.title": "Datenschutzerklärung - ChronosMap",
  "privacy.meta.description": "Datenschutzerklärung für ChronosMap.",
  "privacy.intro": "ChronosMap respektiert deine Privatsphäre. Die App arbeitet mit lokalen Kartendaten, von dir gewählten Dateien und Fotos. Wir erstellen keine Nutzerkonten und sammeln, verkaufen oder teilen personenbezogene Daten nicht aktiv.",
  "privacy.noCollect.title": "Daten, die wir nicht sammeln",
  "privacy.noCollect.item1": "Wir sammeln keinen Namen, keine E-Mail-Adresse, Kontakte oder genaue Standortverläufe.",
  "privacy.noCollect.item2": "Wir verwenden keine Werbe-SDKs Dritter.",
  "privacy.noCollect.item3": "Wir verfolgen keine App-Nutzung für Werbeprofile.",
  "privacy.files.title": "Lokale Dateien und Fotos",
  "privacy.files.body": "Beim Öffnen, Speichern oder Importieren von ChronosMap-Dateien greift die App nur auf ausdrücklich ausgewählte Dateien zu. Beim Fotoimport kann sie Aufnahmezeit und Standort der gewählten Fotos lesen.",
  "privacy.map.title": "Kartendienste",
  "privacy.map.body": "ChronosMap nutzt Apple MapKit zur Kartendarstellung. Kartenkacheln und Basisdienste werden von Apple bereitgestellt und unterliegen Apples Datenschutzrichtlinie.",
  "privacy.sharing.title": "Daten teilen",
  "privacy.sharing.body": "Du kannst .chronosmap-Dateien oder Quellpakete selbst exportieren und teilen. Exportierte Dateien können hinzugefügte Texte, Bilder, Zeiten und Orte enthalten.",
  "privacy.contact.title": "Kontakt",
  "privacy.contact.body": "Bei Fragen zu dieser Datenschutzerklärung kontaktiere uns bitte über die Support-Seite.",
  "support.page.title": "Support - ChronosMap",
  "support.meta.description": "Support-Seite für ChronosMap.",
  "support.intro": "Wenn du ein Problem mit ChronosMap hast oder Feedback zu Kartenbearbeitung, Quelldatenimport oder Fototrajektorien geben möchtest, kontaktiere uns auf GitHub.",
  "support.issue": "Problem melden",
  "support.repo": "Projekt ansehen",
  "support.faq.open": "Wie öffne ich eine Karte? Öffne eine Beispielkarte aus der Bibliothek oder eine .chronosmap-Datei von deinem Gerät.",
  "support.faq.create": "Wie erstelle ich eine Karte? Im Bearbeitungsmodus kannst du Personen, Ereignisse und Trajektorienpunkte hinzufügen oder Punkte aus Fotos importieren.",
  "support.faq.photo": "Was passiert beim Fotoimport? Die App liest Zeit und Ort ausgewählter Fotos und erstellt persönliche Trajektorienpunkte.",
  "support.faq.data": "Werden meine Daten hochgeladen? ChronosMap nutzt vor allem lokale Dateien; exportierte Dateien speicherst und teilst du selbst.",
  "support.faq.platforms": "Welche Plattformen werden unterstützt? ChronosMap ist für iPhone, iPad und Mac.",
  "support.appStore.title": "App Store Informationen",
  "support.appStore.body": "ChronosMap ist als Einmalkauf-App geplant. Nach Veröffentlichung ergänzen wir den App Store Link.",
});

Object.assign(translations.fr, {
  "meta.description": "ChronosMap vous aide à explorer personnes, événements, photos et déplacements dans le temps sur une carte interactive.",
  "home.hero.support": "Obtenir de l'aide",
  "home.hero.privacy": "Voir la confidentialité",
  "home.icon.alt": "Icône de l'app ChronosMap",
  "home.features.lead": "Ouvrez des cartes d'exemple, importez des paquets, éditez vos cartes et explorez les données avec chronologies, lentilles géographiques et couches de densité.",
  "home.feature.timeline.title": "Navigation temporelle",
  "home.feature.timeline.body": "Consultez événements et positions par année, date ou heure, et allez aux moments réels des données.",
  "home.feature.lens.title": "Lentille géographique",
  "home.feature.lens.body": "Sélectionnez une zone sur la carte pour voir les événements et points de trajectoire qui s'y sont produits.",
  "home.feature.editor.title": "Édition de cartes",
  "home.feature.editor.body": "Créez vos cartes avec personnes, événements, points de trajectoire, images et fichiers ChronosMap.",
  "home.photos.point1": "Utilise la position réelle de chaque photo et ne fusionne pas les photos aux coordonnées différentes.",
  "home.photos.point2": "Les photos deviennent du contenu de point de trajectoire, avec des enregistrements image et texte plus riches.",
  "home.photos.point3": "Vos photos sont choisies et enregistrées par vous, pour des cartes privées ou des récits partageables.",
  "home.sample.title": "Carte d'exemple intégrée.",
  "home.sample.lead": "L'app inclut une carte d'exemple de la dynastie Tang en Chine montrant comment organiser personnes, événements et itinéraires par temps et lieu.",
  "home.sample.point1": "Prend en charge cartes d'exemple et cartes créées par l'utilisateur.",
  "home.sample.point2": "Ouverture de fichiers, enregistrer sous, import et export des données sources.",
  "home.sample.point3": "Les données restent locales et sont gérées et partagées par vous.",
  "home.sample.imageAlt": "Illustration de la carte de Chang'an sous les Tang",
  "privacy.page.title": "Politique de confidentialité - ChronosMap",
  "privacy.meta.description": "Politique de confidentialité de ChronosMap.",
  "privacy.intro": "ChronosMap respecte votre vie privée. L'app fonctionne avec des données locales, les fichiers que vous choisissez et les photos que vous choisissez. Nous ne créons pas de comptes et ne collectons, vendons ni partageons activement de données personnelles.",
  "privacy.noCollect.title": "Données non collectées",
  "privacy.noCollect.item1": "Nous ne collectons pas votre nom, e-mail, contacts ni historique de localisation précise.",
  "privacy.noCollect.item2": "Nous n'utilisons pas de SDK publicitaire tiers.",
  "privacy.noCollect.item3": "Nous ne suivons pas l'utilisation de l'app pour créer des profils publicitaires.",
  "privacy.files.title": "Fichiers locaux et photos",
  "privacy.files.body": "Lorsque vous ouvrez, enregistrez ou importez des fichiers ChronosMap, l'app accède seulement aux fichiers choisis. Lors de l'import photo, elle peut lire l'heure et la position des photos sélectionnées.",
  "privacy.map.title": "Services cartographiques",
  "privacy.map.body": "ChronosMap utilise Apple MapKit pour afficher les cartes. Les tuiles et services de base sont fournis par Apple et soumis à sa politique de confidentialité.",
  "privacy.sharing.title": "Partage de données",
  "privacy.sharing.body": "Vous pouvez exporter et partager des fichiers .chronosmap ou des paquets sources. Ils peuvent contenir textes, images, heures et lieux ajoutés par vous.",
  "privacy.contact.title": "Contact",
  "privacy.contact.body": "Pour toute question sur cette politique, contactez-nous via la page d'assistance.",
  "support.page.title": "Assistance - ChronosMap",
  "support.meta.description": "Page d'assistance de ChronosMap.",
  "support.intro": "Si vous rencontrez un problème ou souhaitez donner un avis sur l'édition, l'import source ou les points photo, contactez-nous sur GitHub.",
  "support.issue": "Signaler un problème",
  "support.repo": "Voir le projet",
  "support.faq.open": "Comment ouvrir une carte ? Ouvrez une carte d'exemple depuis la bibliothèque ou un fichier .chronosmap depuis votre appareil.",
  "support.faq.create": "Comment créer une carte ? En mode édition, ajoutez personnes, événements et points, ou importez des points depuis des photos.",
  "support.faq.photo": "Que fait l'import photo ? L'app lit l'heure et la position des photos choisies pour créer des points de trajectoire personnels.",
  "support.faq.data": "Mes données sont-elles téléversées ? ChronosMap utilise surtout des fichiers locaux ; vous enregistrez et partagez les exports.",
  "support.faq.platforms": "Quelles plateformes ? ChronosMap est conçu pour iPhone, iPad et Mac.",
  "support.appStore.title": "Informations App Store",
  "support.appStore.body": "ChronosMap est prévu comme app à achat unique. Le lien App Store sera ajouté après la sortie.",
});

Object.assign(translations.ru, {
  "meta.description": "ChronosMap помогает исследовать людей, события, фотографии и перемещения во времени на интерактивной карте.",
  "home.hero.support": "Получить поддержку",
  "home.hero.privacy": "Политика конфиденциальности",
  "home.icon.alt": "Значок приложения ChronosMap",
  "home.features.lead": "Открывайте примеры карт, импортируйте пакеты, редактируйте свои карты и изучайте данные с временной шкалой, геолинзой и слоями плотности.",
  "home.feature.timeline.title": "Просмотр по времени",
  "home.feature.timeline.body": "Просматривайте события и положения людей по году, дате или часу и переходите к реальным моментам данных.",
  "home.feature.lens.title": "Геолинза",
  "home.feature.lens.body": "Выберите область на карте и увидьте события и точки маршрутов, произошедшие там.",
  "home.feature.editor.title": "Редактор карт",
  "home.feature.editor.body": "Создавайте карты с людьми, событиями, точками маршрута, изображениями и файлами ChronosMap.",
  "home.photos.point1": "Использует фактическое местоположение каждой фотографии и не объединяет снимки с разными координатами.",
  "home.photos.point2": "Фотографии становятся частью точки маршрута, чтобы позже открыть более богатые записи с изображениями и текстом.",
  "home.photos.point3": "Фотоданные выбираете и сохраняете вы; это подходит для личных карт путешествий или общих карт-историй.",
  "home.sample.title": "Встроенная примерная карта.",
  "home.sample.lead": "В приложении есть примерная карта китайской династии Тан, показывающая организацию людей, событий и маршрутов по времени и месту.",
  "home.sample.point1": "Поддерживаются примерные и пользовательские карты.",
  "home.sample.point2": "Открытие из файлов, сохранение как, импорт и экспорт исходных данных.",
  "home.sample.point3": "Данные карты остаются локальными, ими управляете и делитесь вы.",
  "home.sample.imageAlt": "Иллюстрация карты Чанъаня эпохи Тан",
  "privacy.page.title": "Политика конфиденциальности - ChronosMap",
  "privacy.meta.description": "Политика конфиденциальности ChronosMap.",
  "privacy.intro": "ChronosMap уважает вашу конфиденциальность. Приложение работает с локальными картами, выбранными файлами и фотографиями. Мы не создаем аккаунты и не собираем, продаем или передаем личные данные активно.",
  "privacy.noCollect.title": "Данные, которые мы не собираем",
  "privacy.noCollect.item1": "Мы не собираем имя, email, контакты или точную историю местоположений.",
  "privacy.noCollect.item2": "Мы не используем сторонние рекламные SDK.",
  "privacy.noCollect.item3": "Мы не отслеживаем действия в приложении для рекламных профилей.",
  "privacy.files.title": "Локальные файлы и фотографии",
  "privacy.files.body": "При открытии, сохранении или импорте файлов ChronosMap приложение обращается только к явно выбранным файлам. При импорте фотографий оно может читать время съемки и геоданные выбранных фото.",
  "privacy.map.title": "Картографические сервисы",
  "privacy.map.body": "ChronosMap использует Apple MapKit для отображения карт. Тайлы и базовые сервисы предоставляет Apple, на них распространяется политика конфиденциальности Apple.",
  "privacy.sharing.title": "Обмен данными",
  "privacy.sharing.body": "Вы можете сами экспортировать и делиться файлами .chronosmap или исходными пакетами. Они могут содержать добавленные вами тексты, изображения, время и места.",
  "privacy.contact.title": "Контакты",
  "privacy.contact.body": "Если у вас есть вопросы об этой политике, свяжитесь с нами через страницу поддержки.",
  "support.page.title": "Поддержка - ChronosMap",
  "support.meta.description": "Страница поддержки ChronosMap.",
  "support.intro": "Если у вас возникла проблема или есть отзыв о редактировании карт, импорте данных или фото-точках, свяжитесь с нами на GitHub.",
  "support.issue": "Сообщить о проблеме",
  "support.repo": "Открыть проект",
  "support.faq.open": "Как открыть карту? Откройте пример из библиотеки или файл .chronosmap на устройстве.",
  "support.faq.create": "Как создать карту? В режиме редактирования добавляйте людей, события и точки маршрута или импортируйте их из фото.",
  "support.faq.photo": "Что делает импорт фото? Приложение читает время и место выбранных фото и создает личные точки маршрута.",
  "support.faq.data": "Загружаются ли данные? ChronosMap в основном использует локальные файлы; экспорт сохраняете и отправляете вы.",
  "support.faq.platforms": "Какие платформы поддерживаются? ChronosMap создан для iPhone, iPad и Mac.",
  "support.appStore.title": "Информация App Store",
  "support.appStore.body": "ChronosMap планируется как приложение с разовой покупкой. Ссылка App Store будет добавлена после релиза.",
});

function detectLanguage() {
  const saved = localStorage.getItem("chronosmap.site.language");
  if (saved && translations[saved]) return saved;

  for (const language of navigator.languages || [navigator.language]) {
    if (!language) continue;
    if (translations[language]) return language;
    const base = language.split("-")[0];
    if (base === "zh") return language.toLowerCase().includes("hant") ? "zh-Hant" : "zh-Hans";
    const match = languages.find(([code]) => code.split("-")[0] === base);
    if (match) return match[0];
  }
  return "en";
}

function textFor(language, key) {
  return translations[language]?.[key] ?? en[key] ?? key;
}

function applyLanguage(language) {
  const page = document.body.dataset.page || "home";
  document.documentElement.lang = language;
  document.title = textFor(language, `${page}.page.title`);

  document.querySelectorAll("[data-i18n]").forEach((element) => {
    element.textContent = textFor(language, element.dataset.i18n);
  });

  document.querySelectorAll("[data-i18n-attr]").forEach((element) => {
    for (const pair of element.dataset.i18nAttr.split(";")) {
      const [attribute, key] = pair.split(":");
      if (attribute && key) {
        element.setAttribute(attribute, textFor(language, key));
      }
    }
  });

  document.querySelectorAll("[data-language-select]").forEach((select) => {
    select.value = language;
  });

  localStorage.setItem("chronosmap.site.language", language);
}

function setupLanguageSelects(language) {
  document.querySelectorAll("[data-language-select]").forEach((select) => {
    select.innerHTML = "";
    for (const [code, label] of languages) {
      const option = document.createElement("option");
      option.value = code;
      option.textContent = label;
      select.append(option);
    }
    select.value = language;
    select.addEventListener("change", () => applyLanguage(select.value));
  });
}

const initialLanguage = detectLanguage();
setupLanguageSelects(initialLanguage);
applyLanguage(initialLanguage);
